# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.file_uploader:
        class: AppBundle\FileUploader
        arguments:  ['%upload_directory%']

    app.doctrine_file_listener:
            class: AppBundle\EvenListener\FileUploadListener
            arguments:
                - '@app.file_uploader'
                - '%question_directory%'
                - '%video_directory%'
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: postRemove }
